version: '3.4'

name: eshopping
 
services:
  reverseproxy:
   build:
    context: .
    dockerfile: nginx.Dockerfile

  catalogdb:
    image: mongo

  basketdb:
    image: redis:alpine

  discountdb:
    image: postgres

  pgadmin:
    image: dpage/pgadmin4

  orderdb:
    image: mcr.microsoft.com/mssql/server:2017-latest

  rabbitmq:
    image: rabbitmq:3-management-alpine

  portainer:
    image: portainer/portainer-ce

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Catalog.API/Dockerfile

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Basket.API/Dockerfile

  discount.api:
    image: ${DOCKER_REGISTRY-}discountapi
    build:
      context: .
      dockerfile: Discount.API/Dockerfile

  ordering.api:
    image: ${DOCKER_REGISTRY-}orderingapi
    build:
      context: .
      dockerfile: Ordering.API/Dockerfile

  ocelot.api.gateway:
    image: ${DOCKER_REGISTRY-}ocelotapigateway
    build:
       context: .
       dockerfile: Ocelot.ApiGateway/Dockerfile

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2

  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.2

       
        context: .
        dockerfile: Ocelot.ApiGateway/Dockerfile

  identityserver:
    image: ${DOCKER_REGISTRY-}identityserver
    build:
        context: .
        dockerfile: Identity/Dockerfile

volumes:
  mongo_data:
  portainer_data:  
  postgres_data:  
  pgadmin_data:
  elasticsearch-data: